version: '3.9'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis
    ports:
      - "6379:6379"

  listener:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - REDIS_URL=redis://redis:6379
    ports:
      - "3000:3000"
    command: ["node", "src/listener.js"]

  receiver:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - REDIS_URL=redis://redis:6379
    ports:
      - "3001:3000"
    command: ["node", "src/receiver.js"]

volumes:
  mongo-data:
