# Use official Node.js image
FROM node:18

# Set working directory in the container
WORKDIR /expresspubSub

# Copy package.json and install dependencies
COPY package.json ./
RUN npm install

# Copy the rest of the project files
COPY . .

# Expose the app port
EXPOSE 3000

# Start the app
CMD ["node", "listener.js"]
