version: '3.9'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    ports:
      - "6379:6379"

  receiver:
    build: .
    command: node src/receiver.js
    environment:
      - REDIS_HOST=redis
      - MONGO_URL=mongodb://mongo:27017/pubsubDB
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis

  listener:
    build: .
    command: node src/listener.js
    environment:
      - REDIS_HOST=redis
      - MONGO_URL=mongodb://mongo:27017/pubsubDB
    depends_on:
      - mongo
      - redis
